[colors.bright]
black = "#414868"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ECE6A"
magenta = "#bb9af7"
red = "#F7768E"
white = "#c0caf5"
yellow = "#e0af68"

[colors.cursor]
cursor = "#c0caf5"
text = "#1a1b26"

[colors.normal]
black = "#414868"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ECE6A"
magenta = "#bb9af7"
red = "#F7768E"
white = "#A9B1D6"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[colors.selection]
background = "#48B9C7"
text = "CellForeground"

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 10.0

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 2000
multiplier = 5

[selection]
save_to_clipboard = true

[window]
decorations = "full"
opacity = 0.9
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 5
y = 5

[keyboard]
